trigger:
  branches:
    include:
      - Dev  # Match the branch name exactly

stages:
  - stage: Build
    displayName: "Build Solution"
    jobs:
      - job: BuildJob
        pool:
          vmImage: 'windows-latest'
        steps:
          - task: VSBuild@1
            inputs:
              solution: '**/*.sln'
              msbuildArgs: '/p:Configuration=Release'
          - task: CopyFiles@2
            inputs:
              contents: '**/*.dacpac'
              targetFolder: '$(Build.ArtifactStagingDirectory)'
          - task: PublishBuildArtifacts@1
            inputs:
              pathToPublish: '$(Build.ArtifactStagingDirectory)'
              artifactName: 'drop'  # Ensure this matches the folder in DeployToDev stage

  - stage: Test
    displayName: "Run Tests"
    dependsOn: Build  # Run tests after Build stage completes
    jobs:
      - job: TestJob
        pool:
          vmImage: 'windows-latest'
        steps:
          - task: VSTest@2
            inputs:
              testSelector: 'testAssemblies'
              testAssemblyVer2: '**\*test*.dll'

  - stage: DeployToDev
    displayName: "Deploy to QA"
    dependsOn: Test  # Deploy after Test stage completes
    jobs:
      - deployment: DeployToQAJob
        environment: "Dev"  # Specify the Dev environment for deployment
        pool:
          vmImage: 'windows-latest'
        strategy:
          runOnce:
            deploy:
              steps:
                - task: DownloadPipelineArtifact@2
                  inputs:
                    artifactName: 'drop'
                    path: '$(Pipeline.Workspace)/drop'
                
                - task: CopyFiles@2
                  displayName: "Copy .dacpac file to expected location"
                  inputs:
                    SourceFolder: '$(Pipeline.Workspace)/drop/bin/Release'
                    Contents: 'DatabaseSolution.dacpac'
                    TargetFolder: '$(Pipeline.Workspace)/drop'
                
                - task: SqlAzureDacpacDeployment@1
                  inputs:
                    azureSubscription: "vs-enterprise-mpn-miguel-swanepoel (5cb7ba0e-90a4-4d6d-b238-f361039dc222)"
                    ServerName: "ms-automation-sasol-pipeline-sql-dev.database.windows.net"
                    DatabaseName: "ms-automation-sasol-pipeline-sqldb-dev"
                    SqlUsername: "MSAdmin"
                    SqlPassword: "P05it1vity"  # Store as a secret variable in the pipeline
                    DacpacFile: "$(Pipeline.Workspace)/drop/DatabaseSolution.dacpac"
                    DeployType: "DacpacTask"

  - stage: PushToQA
    displayName: "Sync QA Branch"
    dependsOn: DeployToDev
    condition: succeeded()
    jobs:
      - job: PushJob
        displayName: "Push Changes to QA"
        pool:
          vmImage: 'windows-latest'
        steps:
         - checkout: self
         - script: |
              git config user.name "Miguel Swanepoel"
              git config user.email "miguel.swanepoel@firsttech.digital"
              git fetch origin
              git checkout -B QA origin/QA || git checkout -b QA origin/Dev
              git merge origin/Dev
              git push https://<PAT>@dev.azure.com/miguelswanepoel/Pipeline_DB/_git/Pipeline_DB QA
           displayName: "Sync QA Branch"