trigger:
  branches:
    include:
      - Dev

stages:
  - stage: Build
    displayName: "Build Solution"
    jobs:
      - job: BuildJob
        steps:
          - task: VSBuild@1
            inputs:
              solution: '**/*.sln'
              msbuildArgs: '/p:Configuration=Release'
          - task: CopyFiles@2
            inputs:
              contents: '**/*.dacpac'
              targetFolder: '$(Build.ArtifactStagingDirectory)'
          - task: PublishBuildArtifacts@1
            inputs:
              pathToPublish: '$(Build.ArtifactStagingDirectory)'
              artifactName: 'drop'

  - stage: DeployToDev
    displayName: "Deploy to QA"
    dependsOn: Build
    jobs:
      - deployment: DeployToQAJob
        environment: "Dev"  # Specify the Dev environment for deployment
        strategy:
          runOnce:
            deploy:
              steps:
                - task: SqlAzureDacpacDeployment@1
                  inputs:
                    azureSubscription: "vs-enterprise-mpn-miguel-swanepoel (5cb7ba0e-90a4-4d6d-b238-f361039dc222)"
                    ServerName: "ms-automation-sasol-pipeline-sql-dev"
                    DatabaseName: "ms-automation-sasol-pipeline-sqldb-dev"
                    SqlUsername: "Miguel.Swanepoel@firsttech.digital"
                    SqlPassword: "P05it1veP@55word" # Stored as a secret variable
                    DacpacFile: "$(Pipeline.Workspace)/drop/ms-automation-sasol-pipeline-sqldb-dev.dacpac"
                    DeployType: "DacpacTask"

 
