# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

stages:
- stage: Dev
  jobs:
  - job: Deploy
    pool:
      vmImage: 'windows-latest'
    steps:
    - task: DownloadBuildArtifacts@0
      inputs:
        buildType: 'specific'
        project: '$(System.TeamProject)'
        pipeline: '$(Build.DefinitionId)'
        buildVersionToDownload: 'latest'
        downloadPath: '$(System.ArtifactsDirectory)'

    - task: SqlAzureDacpacDeployment@1
      inputs:
        azureSubscription: 'your-azure-subscription'
        ServerName: 'your-server-name.database.windows.net'
        DatabaseName: 'your-database-name'
        SqlUsername: '$(sqlUsername)'
        SqlPassword: '$(sqlPassword)'
        DacpacFile: '$(System.ArtifactsDirectory)/drop/your-database.dacpac'
        DeployType: 'DacpacTask'
        DeploymentAction: 'Publish'

    - task: ManualIntervention@1
      inputs:
        instructions: 'Please approve the deployment to QA.'

- stage: QA
  dependsOn: Dev
  jobs:
  - job: Deploy
    pool:
      vmImage: 'windows-latest'
    steps:
    - task: SqlAzureDacpacDeployment@1
      inputs:
        azureSubscription: 'your-azure-subscription'
        ServerName: 'your-server-name.database.windows.net'
        DatabaseName: 'your-database-name'
        SqlUsername: '$(sqlUsername)'
        SqlPassword: '$(sqlPassword)'
        DacpacFile: '$(System.ArtifactsDirectory)/drop/your-database.dacpac'
        DeployType: 'DacpacTask'
        DeploymentAction: 'Publish'

    - task: ManualIntervention@1
      inputs:
        instructions: 'Please approve the deployment to Prod.'

- stage: Prod
  dependsOn: QA
  jobs:
  - job: Deploy
    pool:
      vmImage: 'windows-latest'
    steps:
    - task: SqlAzureDacpacDeployment@1
      inputs:
        azureSubscription: 'your-azure-subscription'
        ServerName: 'your-server-name.database.windows.net'
        DatabaseName: 'your-database-name'
        SqlUsername: '$(sqlUsername)'
        SqlPassword: '$(sqlPassword)'
        DacpacFile: '$(System.ArtifactsDirectory)/drop/your-database.dacpac'
        DeployType: 'DacpacTask'
        DeploymentAction: 'Publish'

