trigger:
  branches:
    include:
      - main

stages:
  - stage: Build
    displayName: "Build Solution"
    jobs:
      - job: BuildJob
        steps:
          - task: VSBuild@1
            inputs:
              solution: '**/*.sln'
              msbuildArgs: '/p:Configuration=Release'
          - task: CopyFiles@2
            inputs:
              contents: '**/*.dacpac'
              targetFolder: '$(Build.ArtifactStagingDirectory)'
          - task: PublishBuildArtifacts@1
            inputs:
              pathToPublish: '$(Build.ArtifactStagingDirectory)'
              artifactName: 'drop'

  - stage: DeployToDev
    displayName: "Deploy to QA"
    dependsOn: Build
    jobs:
      - deployment: DeployToQAJob
        environment: "Dev"  # Specify the Dev environment for deployment
        strategy:
          runOnce:
            deploy:
              steps:
                - task: SqlAzureDacpacDeployment@1
                  inputs:
                    azureSubscription: "aut-azure-sponsorship"
                    ServerName: "az-sql-mas2022-aut-sa-n"
                    DatabaseName: "Internal.FD.PipelineDB.Demo"
                    SqlUsername: "Miguel.Swanepoel@firsttech.digital"
                    SqlPassword: "P05it1veP@55word" # Stored as a secret variable
                    DacpacFile: "$(Pipeline.Workspace)/drop/Internal.FD.PipelineDB.Demo.dacpac"
                    DeployType: "DacpacTask"

 
